# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Babel Fish' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'YOLOKit'

  target 'Babel FishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Babel FishUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
